# -*- coding: utf-8 -*-
"""hopf_baseline_validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15QHplw9-W2-5kKnKNMO7IrD08lhMWQA8
"""

#图标以及程序正确版 不改动
import sys
import subprocess
import importlib

def _pip_install(pkg: str) -> None:
    """Install a package via pip."""
    print(f"Installing {pkg} ...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", pkg])
    print(f"Installed {pkg}.")

def ensure_import(import_name: str, pip_name: str | None = None):
    """
    Ensure a module can be imported.
    - import_name: name used in `import ...`
    - pip_name: name used in `pip install ...` (defaults to import_name)
    Returns the imported module object.
    """
    if pip_name is None:
        pip_name = import_name
    try:
        return importlib.import_module(import_name)
    except ImportError:
        _pip_install(pip_name)
        return importlib.import_module(import_name)

# ----------------- Imports -----------------

import numpy as np
# from collections import deque  # replaced by numpy circular buffer
import matplotlib.pyplot as plt
from IPython.display import display, clear_output

# FiPy
fipy = ensure_import("fipy", "fipy")
from fipy import *  # keep your original usage style

# tqdm (Notebook flavor). If notebook submodule is missing, fallback to plain tqdm.
try:
    from tqdm.notebook import tqdm
except Exception:
    tqdm_mod = ensure_import("tqdm", "tqdm")
    from tqdm import tqdm

# SciPy: save/load .mat
scipy = ensure_import("scipy", "scipy")
from scipy.io import savemat, loadmat

# Notebook-only: matplotlib inline (safe)
try:
    get_ipython().run_line_magic("matplotlib", "inline")
except Exception:
    pass

print("All packages are ready!")

d1  = 0.3        # diffusion coefficient for Laplacian  (d_1)
d2  = 1.5# -2       # coefficient in the non-local flux     (d_2)
r1  = 0.1           # logistic reaction factor             (f(u)=r1*u*(1-u))
tau =0.002#delay length
L   = np.pi         # domain length
n_init = 2        # k in main_hopf2
u_bar = 1

# grid settings
Nx = 101
dt = 0.0005
Tend = 5  # tital simulation time

# plot
update_step = 200
# save
mat_filename = 'result'

steps = int(round(Tend/dt))

# grid def and initialize
mesh = Grid1D(nx=Nx, Lx=L)

# u: 当前时刻的解 (待求变量)
u = CellVariable(name="u", mesh=mesh, value=0., hasOld=True)

# u_tau: 历史积分后的场 (作为已知系数)
u_tau = CellVariable(name="u_tau", mesh=mesh, value=0.)

# 初始化 u (高斯分布)
x = mesh.cellCenters[0]
#u.setValue(u_bar + 0.02 * np.cos(n_init*np.pi*x / L))
u.setValue(1 + 0.02 * np.cos(n_init*np.pi*x / L))
u.updateOld()

# 可视化初始条件
plt.plot(x, u)
plt.title("u0")

# === 3. 历史数据管理 (环形缓冲区) ===
# 计算需要存储多少步历史
history_steps = int(np.round(2 * tau / dt))
if history_steps % 2 == 0: history_steps += 1

# 初始化历史 buffer — 用预分配的 numpy 环形缓冲区代替 deque
# 避免每步 np.array(deque) 的拷贝开销
u_history_buf = np.zeros((history_steps, Nx))
for i in range(history_steps):
    u_history_buf[i, :] = u.value.copy()
buf_idx = 0  # 环形缓冲区写指针

# 预计算权重 h(s) (同 MATLAB 逻辑)
s_vec = np.linspace(-2*tau, 0, history_steps)
h_weights = np.zeros(history_steps)
for i, s in enumerate(s_vec):
    if -2*tau <= s < -tau:
        h_weights[i] = (1/tau**2)*s + (2/tau)
    elif -tau <= s <= 0:
        h_weights[i] = -(1/tau**2)*s
# 归一化权重 (关键！)
h_weights = h_weights / np.sum(h_weights)

# 预计算环形缓冲区的权重索引顺序（从最老到最新）
# 这样每步只需要根据 buf_idx 重排权重，而不是重建数组
h_weights_buf = h_weights.copy()  # 会在循环内按 buf_idx 重排

# 可视化权重
plt.plot(s_vec, h_weights)
print(f"sum of h_win= {np.sum(h_weights)}")

# 对流项采用迎风格式 d_2 \nabla \cdot ( u \nabla  u_\tau)
velocity = d2 * u_tau.faceGrad
advection = UpwindConvectionTerm(coeff=velocity, var=u)
# 反应项，部分隐式法 reaction = r1 * u * (1-u)
reaction_explicit = r1 * u
reaction_implicit = ImplicitSourceTerm(coeff=-r1*u, var=u)
reaction = reaction_explicit + reaction_implicit
# PDE, 隐式方法
eq = (TransientTerm(var=u) == DiffusionTerm(coeff=d1, var=u) + advection + reaction)

# === 5. 仿真循环 ===

fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(14, 6))
# [上图] 实时波形
line, = ax1.plot(x, u.value, 'b-', linewidth=2)
ax1.set_ylim(0, 3)
ax1.set_ylabel('u(x, t)')
ax1.set_xlabel('Space (x)')
ax1.set_title('u(x) Current State')
ax1.grid(True)

# [下图] (X, t) 热力图容器
# 我们预先分配一个全 0 的矩阵来存储所有结果
# 矩阵形状: [时间步数, 空间点数]
solution_matrix = np.zeros((steps, Nx))
solution_matrix[0, :] = u.value # 存入初始状态
# 初始化热力图对象 (类似于 imagesc 或 surf view 2)
# extent 参数用于设置坐标轴的真实物理范围 [x_min, x_max, t_max, t_min]
#heatmap = ax2.imshow(solution_matrix, aspect='auto', cmap='jet', vmin=0, vmax=2.5,
                    # extent=[0, L, steps*dt, 0])
                     # 注意：extent 的 t 顺序可能需要根据习惯调整，这里设为 0 在上
heatmap = ax2.imshow(
    solution_matrix,
    aspect='auto',
    cmap='jet',
    vmin=0, vmax=2.5,
    extent=[0, L, 0, steps*dt],
    origin='lower'
)


ax2.set_xlabel('x')
ax2.set_ylabel('t')
ax2.set_title('u(x,t)')
#plt.colorbar(heatmap, ax=ax2, label='Concentration u')

# ax3 绘制 残差图
residences = np.zeros((steps,))
resid_line, = ax3.plot(range(steps), residences)
ax3.set_ylim(0, 1e-3)
ax3.set_ylabel("Residence")
ax3.set_xlabel('Step')
ax3.set_title('Residence of sweep')
ax3.grid(True)

plt.tight_layout()

try:
    obs_display = display(fig, display_id=True)
except Exception:
    obs_display = None
plt.close(fig)

pbar = tqdm(range(steps))

MAX_SWEEP = 500  # sweep 最大迭代次数，防止卡死

for step in pbar:
    # --- A. 计算 u_tau (积分) ---
    # 环形缓冲区：按正确时间顺序排列权重与历史数据做点积
    # buf_idx 指向下一个要写入的位置 = 最老的数据位置
    # 所以从 buf_idx 开始读就是从最老到最新的顺序
    order = np.arange(buf_idx, buf_idx + history_steps) % history_steps
    u_tau_val = np.dot(h_weights, u_history_buf[order])

    # 更新 FiPy 变量 u_tau 的值
    u_tau.setValue(u_tau_val)

    # --- B. 求解 PDE ---
    resid = 1e6
    cnt = 0
    last_resid = resid
    while resid > 1e-4 and cnt < MAX_SWEEP:
        resid = eq.sweep(var=u, dt=dt)
        cnt += 1
        if abs(resid - last_resid) < 1e-5:
            break
        last_resid = resid

    # --- C. 更新历史 ---
    u_history_buf[buf_idx, :] = u.value.copy()
    buf_idx = (buf_idx + 1) % history_steps

    solution_matrix[step, :] = u.value
    residences[step] = resid
    u.updateOld()
    pbar.set_postfix({'Resid': f'{resid:2e}'})

    # ===== 可视化更新 =====
    if step % update_step == 0 or step == steps - 1:
        line.set_ydata(u.value)
        heatmap.set_data(solution_matrix)
        heatmap.set_extent([0, L, 0, steps*dt])
        ax2.set_xlim(0, L)
        ax2.set_ylim(0, steps*dt)
        ax2.autoscale(False)
        ax2.tick_params(direction='in', length=4, width=1)
        ax2.spines['top'].set_visible(False)
        ax2.spines['right'].set_visible(False)
        ax2.spines['left'].set_visible(False)
        ax2.tick_params(axis='y', length=0)
        resid_line.set_ydata(residences)
        if obs_display is not None:
            obs_display.update(fig)
        else:
            plt.pause(0.001)
# =========================
# 保存 ax2 单独图片
# =========================

fig.canvas.draw()

bbox = ax2.get_tightbbox(fig.canvas.get_renderer())
bbox = bbox.transformed(fig.dpi_scale_trans.inverted())
fig.savefig("ax2_heatmap.eps", bbox_inches=bbox, format="eps")
#fig.savefig("ax2_heatmap.pdf", bbox_inches=bbox, format="pdf")
#fig.savefig("ax2_heatmap.png", bbox_inches=bbox, dpi=300)
# 去边框（论文级风格）
ax2.spines['top'].set_visible(False)
ax2.spines['right'].set_visible(False)
ax2.spines['left'].set_visible(False)

plt.close()

bw = 0.01
fig, ax2 = plt.subplots(1, 1, figsize=(6, 6))
#heatmap = ax2.imshow(solution_matrix, aspect='auto', cmap='jet', vmin=1-bw, vmax=1+bw,
                  #   extent=[0, L, 0, steps*dt],  origin='lower' )
                     # 注意：extent 的 t 顺序可能需要根据习惯调整，这里设为 0 在上
heatmap = ax2.imshow(
    solution_matrix,
    aspect='auto',
    cmap='jet',
    vmin=0, vmax=2.5,
    extent=[0, L, 0, steps*dt],
    origin='lower'
)


ax2.set_xlabel('x')
ax2.set_ylabel('t')
ax2.set_title('u(x,t)')
plt.colorbar(heatmap, ax=ax2, label='Concentration u')


