function val = G_fun(omega, epsilon, n, params)
%G_FUN Scalar Hopf search equation G(omega, epsilon) = 0 from budengyao.pdf.
%   This is the explicit form of equation (0.10), obtained from
%   sin^2(omega * epsilon) + cos^2(omega * epsilon) = 1 after substituting
%   the right-hand sides from equations (0.8) and (0.9).

mu = mu_n(n, params.L);
drift = params.d1 * mu - params.f_u;

a = epsilon * (params.tau - epsilon) * params.tau ...
    / (4.0 * params.d2 * params.u_bar * mu);
b = epsilon * (params.tau - epsilon) * params.tau * drift^2 ...
    / (4.0 * params.d2 * params.u_bar * mu);

val = a .* omega.^6 ...
    + b .* omega.^4 ...
    + epsilon .* sin(omega .* params.tau) .* omega.^3 ...
    - drift .* (params.tau - epsilon + epsilon .* cos(omega .* params.tau)) ...
        .* omega.^2 ...
    + (2.0 * params.d2 * params.u_bar * mu / params.tau) ...
        .* (cos(omega .* params.tau) - 1.0);
end
