function write_hopf_points_csv(points, output_path)
%WRITE_HOPF_POINTS_CSV Export verified Hopf points to a CSV file.

if isempty(points)
    table_out = table([], [], [], [], [], [], ...
        'VariableNames', {'n', 'k', 'epsilon_star', 'omega_star', ...
        'residual_abs', 're_dlambda_depsilon'});
    writetable(table_out, output_path);
    return;
end

table_out = table( ...
    [points.n].', ...
    [points.k_est].', ...
    [points.epsilon_refined].', ...
    [points.omega_refined].', ...
    abs([points.delta_value].'), ...
    real([points.dlambda_depsilon].'), ...
    'VariableNames', {'n', 'k', 'epsilon_star', 'omega_star', ...
    'residual_abs', 're_dlambda_depsilon'});

writetable(table_out, output_path);
end
